server:
  port: 8080

spring:
  profiles:
    active: dev

  main:
    allow-circular-references: true

  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}

  data: # Spring Boot 3.x 使用这个前缀
    redis:
      host: ${sky.redis.host}  # Redis服务器地址
      port: ${sky.redis.port}      # Redis服务器端口
      password:      # 密码，没有则留空或注释掉
      database:  ${sky.redis.database}      #数据库的索引，使用0号数据库，在redis客户端中可以查看访问

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 用户端JWT配置
    user-secret-key: itcast
    user-ttl: 7200000000
    user-token-name: authentication
  wechat:
    appid: wx1fc8a9d531b6a04e
    secret: 18f69ccb6183568efadca3531c4e4a50
